### ISSUE TITLE
调用微信登录时,报空引用:ShareConfig.isDebug()' on a null object reference

### ISSUE THREAD

**Issue by jesse920524** [shaohui10086/ShareUtil#21]
04-21 10:59:31.407 9307-9307/xique.yinwei.ren E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: xique.yinwei.ren, PID: 9307
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{xique.yinwei.ren/me.shaohui.shareutil._ShareActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean me.shaohui.shareutil.ShareConfig.isDebug()' on a null object reference
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean me.shaohui.shareutil.ShareConfig.isDebug()' on a null object reference
                                                                    at me.shaohui.shareutil.ShareLogger.i(ShareLogger.java:14)
                                                                    at me.shaohui.shareutil._ShareActivity.onCreate(_ShareActivity.java:36)
                                                                    at android.app.Activity.performCreate(Activity.java:6251)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jesse920524** [comment]
#### 自问自答:报以上错误是因为ShareConfig没有正确的初始化.

经过我的调试,微博登录已经好用了.
我compile的是withJar的ShareUtil版本
感谢作者.
